# Generated by Django 5.2.8 on 2025-11-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='veiculo_descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='veiculo_descricao',
            field=models.CharField(blank=True, help_text='Ex.: SUV prata, Sedan preto, Moto vermelha...', max_length=100, null=True),
        ),
    ]
