# Generated by Django 5.2.8 on 2025-11-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documento_placa_documento_veiculo_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ramo',
            field=models.CharField(choices=[('GERAL', 'Geral / Outros'), ('AUTO', 'Automotivo (lava jato, oficina, etc.)')], default='GERAL', max_length=20),
        ),
    ]
